[theme]
base = "dark"
backgroundColor = "#1e1e1e"          # elegant dark gray
secondaryBackgroundColor = "#2c2c2c" # slightly lighter gray for widgets
textColor = "#f5f5f5"                # soft off-white
primaryColor = "#4CAF50"            # a muted green accent (can be changed)
